name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Run Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle --build-cache test
